POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name":"Nicolas Kraide",
  "email":"nicolas.kraide@gmail.com"
}

###

GET http://localhost:3333/invites/:kraide13

###

GET http://localhost:3333/subscribers/:kraide13/ranking/clicks