POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name":"teste5",
  "email":"teste45@gmail.com",
  "referrer": "80e25273-266e-4fda-af6e-f1754e0eaf2e"
}


###
GET http://localhost:3333/invites/edfea5bd-328c-439f-a725-2da8eb2a3fa3


###
GET http://localhost:3333/subscribers/edfea5bd-328c-439f-a725-2da8eb2a3fa3/ranking/clicks


### 
GET http://localhost:3333/subscribers/80e25273-266e-4fda-af6e-f1754e0eaf2e/ranking/count


###
GET http://localhost:3333/subscribers/edfea5bd-328c-439f-a725-2da8eb2a3fa3/ranking/position


###'
GET http://localhost:3333/ranking