POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name":"convidassfdad",
  "email":"convsidasfadsd@gmail.com",
  "referrer": "edfea5bd-328c-439f-a725-2da8eb2a3fa3"
}


###
GET http://localhost:3333/invites/edfea5bd-328c-439f-a725-2da8eb2a3fa3


###
GET http://localhost:3333/subscribers/edfea5bd-328c-439f-a725-2da8eb2a3fa3/ranking/clicks


### 
GET http://localhost:3333/subscribers/edfea5bd-328c-439f-a725-2da8eb2a3fa3/ranking/count